import Cocoa

/// One remembered clipboard item.
struct ClipEntry {
    enum Kind { case text(String); case image(NSImage) }
    let kind: Kind
    let date: Date
}

/// Watches the general pasteboard and keeps a rolling history of recent copies
/// (text + images). Password managers mark sensitive copies with de-facto
/// "concealed/transient" pasteboard types, which are respected and skipped.
/// Text is persisted across launches; images are kept for the session only.
final class ClipboardHistory {
    static let shared = ClipboardHistory()

    private(set) var entries: [ClipEntry] = []
    private let maxEntries = 20
    private var timer: Timer?
    private var lastChange = NSPasteboard.general.changeCount

    var isRunning: Bool { timer != nil }

    func start() {
        guard timer == nil else { return }
        loadPersisted()
        lastChange = NSPasteboard.general.changeCount
        // No system notification exists for pasteboard changes, so poll — the
        // standard approach for clipboard managers.
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in self?.poll() }
        RunLoop.main.add(t, forMode: .common)
        timer = t
        Logger.log("Clipboard history: on")
    }

    func stop() {
        timer?.invalidate(); timer = nil
        Logger.log("Clipboard history: off")
    }

    func clear() {
        entries.removeAll()
        persist()
        NotificationCenter.default.post(name: .windowSnapClipboardChanged, object: nil)
    }

    /// Apply the current "persist to disk" setting: writes the in-memory history
    /// when on, or deletes the on-disk store when off. Call after the toggle flips.
    func syncPersistence() { persist() }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChange else { return }
        lastChange = pb.changeCount

        let types = pb.types ?? []
        let concealed = [NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
                         NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
                         NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")]
        if concealed.contains(where: { types.contains($0) }) { return }

        if let s = pb.string(forType: .string),
           !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            add(.text(s))
        } else if let img = NSImage(pasteboard: pb) {
            add(.image(img))
        }
    }

    private func add(_ kind: ClipEntry.Kind) {
        // Skip an immediate duplicate of the newest text entry.
        if case .text(let s) = kind, case .text(let t)? = entries.first?.kind, s == t { return }
        entries.insert(ClipEntry(kind: kind, date: Date()), at: 0)
        if entries.count > maxEntries { entries.removeLast(entries.count - maxEntries) }
        persist()
        NotificationCenter.default.post(name: .windowSnapClipboardChanged, object: nil)
    }

    // MARK: Persistence (text only — keeps the store small)

    private struct PersistedText: Codable { let text: String; let date: Date }

    private var storeURL: URL {
        let dir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("WindowSnap", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("clipboard-history.json")
    }

    /// How long a persisted clip is allowed to live on disk. Older entries are
    /// dropped on load so stale (possibly sensitive) copies don't linger forever.
    private let maxPersistedAge: TimeInterval = 14 * 24 * 60 * 60   // 14 days

    private func persist() {
        // Respect the privacy opt-out: keep history in memory only, and remove any
        // file that a previous (persisting) session left behind.
        guard Settings.shared.clipboardPersistToDisk else {
            try? FileManager.default.removeItem(at: storeURL)
            return
        }
        let texts: [PersistedText] = entries.compactMap {
            if case .text(let s) = $0.kind { return PersistedText(text: s, date: $0.date) }
            return nil
        }
        if let data = try? JSONEncoder().encode(texts) { try? data.write(to: storeURL, options: .atomic) }
    }

    private func loadPersisted() {
        guard Settings.shared.clipboardPersistToDisk else { return }
        guard entries.isEmpty,
              let data = try? Data(contentsOf: storeURL),
              let texts = try? JSONDecoder().decode([PersistedText].self, from: data) else { return }
        // Drop anything past the age cap.
        let cutoff = Date().addingTimeInterval(-maxPersistedAge)
        entries = texts.filter { $0.date >= cutoff }.map { ClipEntry(kind: .text($0.text), date: $0.date) }
    }
}

// MARK: - Picker panel

/// A searchable floating list of clipboard history. Type to filter, ↑/↓ to move,
/// Return to pick (copies it, and — if enabled — pastes into the app that was
/// frontmost), Esc to dismiss.
final class ClipboardHistoryPanel: NSObject, NSTableViewDataSource, NSTableViewDelegate,
                                   NSTextFieldDelegate, NSWindowDelegate {
    static let shared = ClipboardHistoryPanel()

    private var panel: NSPanel?
    private var searchField: NSTextField!
    private var table: NSTableView!
    private var filtered: [ClipEntry] = []
    private var frontApp: NSRunningApplication?

    func show() {
        if panel != nil { close(); return }   // toggle
        frontApp = NSWorkspace.shared.frontmostApplication
        filtered = ClipboardHistory.shared.entries
        build()
        NotificationCenter.default.addObserver(self, selector: #selector(reloadLive),
                                               name: .windowSnapClipboardChanged, object: nil)
    }

    @objc private func reloadLive() { applyFilter(searchField?.stringValue ?? "") }

    private func build() {
        let w: CGFloat = 380, h: CGFloat = 440
        let p = NSPanel(contentRect: NSRect(x: 0, y: 0, width: w, height: h),
                        styleMask: [.titled, .closable], backing: .buffered, defer: false)
        p.title = "Clipboard History"
        p.isFloatingPanel = true
        p.level = .floating
        p.becomesKeyOnlyIfNeeded = false
        p.hidesOnDeactivate = false
        p.isReleasedWhenClosed = false
        p.delegate = self

        let content = p.contentView!
        searchField = NSTextField()
        searchField.placeholderString = "Search…"
        searchField.delegate = self
        searchField.translatesAutoresizingMaskIntoConstraints = false

        table = NSTableView()
        let col = NSTableColumn(identifier: NSUserInterfaceItemIdentifier("clip"))
        col.resizingMask = .autoresizingMask
        table.addTableColumn(col)
        table.headerView = nil
        table.rowHeight = 30
        table.dataSource = self
        table.delegate = self
        table.target = self
        table.doubleAction = #selector(chooseClicked)

        let scroll = NSScrollView()
        scroll.documentView = table
        scroll.hasVerticalScroller = true
        scroll.translatesAutoresizingMaskIntoConstraints = false

        let clearBtn = NSButton(title: "Clear", target: self, action: #selector(clearHistory))
        clearBtn.bezelStyle = .rounded
        clearBtn.translatesAutoresizingMaskIntoConstraints = false
        let hint = NSTextField(labelWithString: "Return to paste · Esc to close")
        hint.font = .systemFont(ofSize: 10)
        hint.textColor = .tertiaryLabelColor
        hint.translatesAutoresizingMaskIntoConstraints = false

        content.addSubview(searchField)
        content.addSubview(scroll)
        content.addSubview(clearBtn)
        content.addSubview(hint)
        NSLayoutConstraint.activate([
            searchField.topAnchor.constraint(equalTo: content.topAnchor, constant: 10),
            searchField.leadingAnchor.constraint(equalTo: content.leadingAnchor, constant: 10),
            searchField.trailingAnchor.constraint(equalTo: content.trailingAnchor, constant: -10),
            scroll.topAnchor.constraint(equalTo: searchField.bottomAnchor, constant: 8),
            scroll.leadingAnchor.constraint(equalTo: content.leadingAnchor, constant: 10),
            scroll.trailingAnchor.constraint(equalTo: content.trailingAnchor, constant: -10),
            scroll.bottomAnchor.constraint(equalTo: clearBtn.topAnchor, constant: -8),
            clearBtn.leadingAnchor.constraint(equalTo: content.leadingAnchor, constant: 10),
            clearBtn.bottomAnchor.constraint(equalTo: content.bottomAnchor, constant: -10),
            hint.trailingAnchor.constraint(equalTo: content.trailingAnchor, constant: -12),
            hint.centerYAnchor.constraint(equalTo: clearBtn.centerYAnchor),
        ])

        let mouse = NSEvent.mouseLocation
        let screen = NSScreen.screens.first(where: { $0.frame.contains(mouse) }) ?? NSScreen.main
        let vis = screen?.visibleFrame ?? NSRect(x: 0, y: 0, width: w, height: h)
        p.setFrameOrigin(NSPoint(x: vis.midX - w / 2, y: vis.midY - h / 2))

        panel = p
        NSApp.activate()
        p.makeKeyAndOrderFront(nil)
        p.makeFirstResponder(searchField)
        if !filtered.isEmpty { table.selectRowIndexes([0], byExtendingSelection: false) }
    }

    private func applyFilter(_ q: String) {
        let all = ClipboardHistory.shared.entries
        if q.isEmpty {
            filtered = all
        } else {
            let ql = q.lowercased()
            filtered = all.filter {
                switch $0.kind {
                case .text(let s): return s.lowercased().contains(ql)
                case .image: return "image".contains(ql)
                }
            }
        }
        table?.reloadData()
        if !filtered.isEmpty { table.selectRowIndexes([0], byExtendingSelection: false) }
    }

    // MARK: Search field key handling

    func controlTextDidChange(_ obj: Notification) { applyFilter(searchField.stringValue) }

    func control(_ control: NSControl, textView: NSTextView, doCommandBy sel: Selector) -> Bool {
        switch sel {
        case #selector(NSResponder.moveDown(_:)):     moveSelection(1);  return true
        case #selector(NSResponder.moveUp(_:)):       moveSelection(-1); return true
        case #selector(NSResponder.insertNewline(_:)): chooseSelected(); return true
        case #selector(NSResponder.cancelOperation(_:)): close();        return true
        default: return false
        }
    }

    private func moveSelection(_ delta: Int) {
        guard !filtered.isEmpty else { return }
        let cur = table.selectedRow < 0 ? 0 : table.selectedRow
        let next = min(max(0, cur + delta), filtered.count - 1)
        table.selectRowIndexes([next], byExtendingSelection: false)
        table.scrollRowToVisible(next)
    }

    // MARK: Table

    func numberOfRows(in tableView: NSTableView) -> Int { filtered.count }

    func tableView(_ t: NSTableView, viewFor col: NSTableColumn?, row: Int) -> NSView? {
        let cell = NSTableCellView()
        let label = NSTextField(labelWithString: Self.preview(filtered[row]))
        label.lineBreakMode = .byTruncatingTail
        label.translatesAutoresizingMaskIntoConstraints = false
        cell.addSubview(label)
        NSLayoutConstraint.activate([
            label.leadingAnchor.constraint(equalTo: cell.leadingAnchor, constant: 4),
            label.trailingAnchor.constraint(equalTo: cell.trailingAnchor, constant: -4),
            label.centerYAnchor.constraint(equalTo: cell.centerYAnchor),
        ])
        return cell
    }

    static func preview(_ e: ClipEntry) -> String {
        switch e.kind {
        case .text(let s):
            let one = s.replacingOccurrences(of: "\n", with: " ")
                .trimmingCharacters(in: .whitespacesAndNewlines)
            return one.count > 90 ? String(one.prefix(90)) + "…" : one
        case .image(let img):
            return "🖼 Image \(Int(img.size.width))×\(Int(img.size.height))"
        }
    }

    @objc private func chooseClicked() { chooseSelected() }
    @objc private func clearHistory() {
        ClipboardHistory.shared.clear(); filtered = []; table.reloadData()
    }

    private func chooseSelected() {
        let row = table.selectedRow
        guard row >= 0, row < filtered.count else { return }
        let entry = filtered[row]
        let pb = NSPasteboard.general
        pb.clearContents()
        switch entry.kind {
        case .text(let s):  pb.setString(s, forType: .string)
        case .image(let i): pb.writeObjects([i])
        }
        close()
        // Return focus to the app that was frontmost, then synthesize ⌘V.
        if Settings.shared.clipboardAutoPaste, let app = frontApp {
            app.activate()
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.12) { Self.synthesizePaste() }
        }
    }

    private static func synthesizePaste() {
        let src = CGEventSource(stateID: .combinedSessionState)
        let v: CGKeyCode = 9   // 'v'
        let down = CGEvent(keyboardEventSource: src, virtualKey: v, keyDown: true)
        down?.flags = .maskCommand
        let up = CGEvent(keyboardEventSource: src, virtualKey: v, keyDown: false)
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }

    private func close() { panel?.close() }

    func windowWillClose(_ notification: Notification) {
        NotificationCenter.default.removeObserver(self, name: .windowSnapClipboardChanged, object: nil)
        panel = nil
    }
}

// MARK: - In-window Clipboard tab

// MARK: - Clipboard history tab

/// In-window clipboard history: a searchable list; double-click or Copy puts an
/// item back on the clipboard. (Auto-paste lives in the floating picker, since
/// here the app window itself is frontmost.)
final class ClipboardHistoryPane: NSView, NSTableViewDataSource, NSTableViewDelegate, NSTextFieldDelegate {
    private let table = NSTableView()
    private let searchField = NSTextField()
    private var filtered: [ClipEntry] = []

    override init(frame frameRect: NSRect) {
        super.init(frame: frameRect)
        build()
        NotificationCenter.default.addObserver(self, selector: #selector(reload),
                                               name: .windowSnapClipboardChanged, object: nil)
        reload()
    }
    required init?(coder: NSCoder) { fatalError() }

    private func build() {
        searchField.placeholderString = "Search…"
        searchField.delegate = self
        searchField.translatesAutoresizingMaskIntoConstraints = false

        let col = NSTableColumn(identifier: NSUserInterfaceItemIdentifier("clip"))
        col.resizingMask = .autoresizingMask
        table.addTableColumn(col); table.headerView = nil; table.rowHeight = 28
        table.dataSource = self; table.delegate = self
        table.target = self; table.doubleAction = #selector(copySelected)

        let scroll = NSScrollView(); scroll.documentView = table
        scroll.hasVerticalScroller = true; scroll.translatesAutoresizingMaskIntoConstraints = false

        let copyBtn = NSButton(title: "Copy", target: self, action: #selector(copySelected))
        let clearBtn = NSButton(title: "Clear", target: self, action: #selector(clearAll))
        for b in [copyBtn, clearBtn] { b.bezelStyle = .rounded; b.translatesAutoresizingMaskIntoConstraints = false }
        let hint = NSTextField(labelWithString: "Double-click or Copy to put an item back on the clipboard.")
        hint.font = .systemFont(ofSize: 10); hint.textColor = .tertiaryLabelColor
        hint.translatesAutoresizingMaskIntoConstraints = false

        addSubview(searchField); addSubview(scroll); addSubview(copyBtn); addSubview(clearBtn); addSubview(hint)
        NSLayoutConstraint.activate([
            searchField.topAnchor.constraint(equalTo: topAnchor, constant: 14),
            searchField.leadingAnchor.constraint(equalTo: leadingAnchor, constant: 16),
            searchField.trailingAnchor.constraint(equalTo: trailingAnchor, constant: -16),
            scroll.topAnchor.constraint(equalTo: searchField.bottomAnchor, constant: 8),
            scroll.leadingAnchor.constraint(equalTo: leadingAnchor, constant: 16),
            scroll.trailingAnchor.constraint(equalTo: trailingAnchor, constant: -16),
            scroll.bottomAnchor.constraint(equalTo: copyBtn.topAnchor, constant: -8),
            copyBtn.leadingAnchor.constraint(equalTo: leadingAnchor, constant: 16),
            copyBtn.bottomAnchor.constraint(equalTo: bottomAnchor, constant: -14),
            clearBtn.leadingAnchor.constraint(equalTo: copyBtn.trailingAnchor, constant: 8),
            clearBtn.centerYAnchor.constraint(equalTo: copyBtn.centerYAnchor),
            hint.trailingAnchor.constraint(equalTo: trailingAnchor, constant: -16),
            hint.centerYAnchor.constraint(equalTo: copyBtn.centerYAnchor),
        ])
    }

    @objc func reload() { applyFilter(searchField.stringValue) }

    private func applyFilter(_ q: String) {
        let all = ClipboardHistory.shared.entries
        let ql = q.lowercased()
        filtered = q.isEmpty ? all : all.filter {
            if case .text(let s) = $0.kind { return s.lowercased().contains(ql) }
            return "image".contains(ql)
        }
        table.reloadData()
    }

    func controlTextDidChange(_ obj: Notification) { applyFilter(searchField.stringValue) }

    func numberOfRows(in tableView: NSTableView) -> Int { filtered.count }
    func tableView(_ t: NSTableView, viewFor c: NSTableColumn?, row: Int) -> NSView? {
        let cell = NSTableCellView()
        let l = NSTextField(labelWithString: ClipboardHistoryPanel.preview(filtered[row]))
        l.lineBreakMode = .byTruncatingTail; l.translatesAutoresizingMaskIntoConstraints = false
        cell.addSubview(l)
        NSLayoutConstraint.activate([
            l.leadingAnchor.constraint(equalTo: cell.leadingAnchor, constant: 4),
            l.trailingAnchor.constraint(equalTo: cell.trailingAnchor, constant: -4),
            l.centerYAnchor.constraint(equalTo: cell.centerYAnchor)])
        return cell
    }

    @objc private func copySelected() {
        let r = table.selectedRow; guard r >= 0, r < filtered.count else { return }
        let pb = NSPasteboard.general; pb.clearContents()
        switch filtered[r].kind {
        case .text(let s):  pb.setString(s, forType: .string)
        case .image(let i): pb.writeObjects([i])
        }
    }
    @objc private func clearAll() { ClipboardHistory.shared.clear() }
}
